# Generated by Django 3.0.7 on 2021-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('coin_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Coin Suggestion',
                'verbose_name_plural': 'Coin Suggestions',
            },
        ),
    ]
