# Generated by Django 3.0.7 on 2021-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210523_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsuggestion',
            name='coin_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
